### PR TITLE
Carry patch for skipping diskDiffOperation when cloning

### PR DESCRIPTION
**Pull request by patrickdillon**
For https://bugzilla.redhat.com/show_bug.cgi?id=1825323 we need to carry the patch from upstream PR: terraform-providers#1075

### CODE REVIEW

**Comment by patrickdillon** [comment]
Successful testing of openshift/installer#3603 shows that this patch successfully allows us to clone thin-provisioned disks. I think this is ready to merge.

**Comment by abhinavdahiya** [comment]
LGTM

**Comment by abhinavdahiya** [comment]
@patrickdillon pushed [**v1.18.1-openshift-1**](https://github.com/openshift/terraform-provider-vsphere/tree/v1.18.1-openshift-1) tag for help with vendoring.

**Comment by mtnbikenc** [comment]
Upstream: https://github.com/hashicorp/terraform-provider-vsphere/pull/1075

**Pull request merged**
